### ISSUE TITLE
panic on podman push

### ISSUE THREAD

**Issue by timonegk** [containers/image#750]
When executing `podman push registry.mydomain.com/imagename`, I get the following error:
```
Getting image source signatures
Copying blob 3a8defd3c960 [=======>------------------------------] 10.0MiB / 50.0MiB
Copying blob 002555c37f66 [=============>------------------------] 6.0MiB / 16.4MiB
Copying blob 831b66a484dc [=>------------------------------------] 7.3MiB / 113.7MiB
Copying blob 9cc9add37421 [>-------------------------------------] 7.3MiB / 475.4MiB
Copying blob ccf71bd6dffe skipped: already exists
Copying blob f256d8ec889c skipped: already exists
Copying blob e1ca698764a7 [--------------------------------------] 8b / 8.5MiB
Copying blob 6aad20fe678c [--------------------------------------] 8b / 2.2MiB
panic: d.nx != 0

goroutine 86 [running]:
crypto/sha256.(*digest).checkSum(0xc0007d8b40, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.11/src/crypto/sha256/sha256.go:253 +0x1e9
crypto/sha256.(*digest).Sum(0xc0003fe980, 0x0, 0x0, 0x0, 0xc0007d8c68, 0xf98d1219, 0xb1cdc63ac2ffd3e2)
	/usr/lib/go-1.11/src/crypto/sha256/sha256.go:229 +0x69
github.com/opencontainers/go-digest.NewDigest(0x191b791, 0x6, 0x1b7c4c0, 0xc0003fe980, 0x18, 0xc0007d8c60)
	vendor/github.com/opencontainers/go-digest/digest.go:40 +0x46
github.com/opencontainers/go-digest.(*digester).Digest(0xc00056ca80, 0x1b6ccd8, 0xc0006feec0)
	vendor/github.com/opencontainers/go-digest/digester.go:38 +0x49
github.com/containers/image/v5/docker.(*dockerImageDestination).PutBlob(0xc000274de0, 0x1b7a040, 0xc00003e138, 0x1b62680, 0xc00036a068, 0x0, 0x0, 0xffffffffffffffff, 0x0, 0x0, ...)
	vendor/github.com/containers/image/v5/docker/docker_image_dest.go:169 +0x669
github.com/containers/image/v5/copy.(*copier).copyBlobFromStream(0xc0001048f0, 0x1b7a040, 0xc00003e138, 0x7fb12c201238, 0xc0003c89a0, 0xc0004be550, 0x47, 0x1068400, 0x0, 0x0, ...)
	vendor/github.com/containers/image/v5/copy/copy.go:1167 +0x40b
github.com/containers/image/v5/copy.(*imageCopier).copyLayerFromStream(0xc000275260, 0x1b7a040, 0xc00003e138, 0x7fb12c201238, 0xc0003c89a0, 0xc0004be550, 0x47, 0x1068400, 0x0, 0x0, ...)
	vendor/github.com/containers/image/v5/copy/copy.go:1030 +0x191
github.com/containers/image/v5/copy.(*imageCopier).copyLayer(0xc000275260, 0x1b7a040, 0xc00003e138, 0xc0004be550, 0x47, 0x1068400, 0x0, 0x0, 0x0, 0x0, ...)
	vendor/github.com/containers/image/v5/copy/copy.go:975 +0x39f
github.com/containers/image/v5/copy.(*imageCopier).copyLayers.func1(0x2, 0xc0004be550, 0x47, 0x1068400, 0x0, 0x0, 0x0, 0x0, 0xc000386300, 0x26, ...)
	vendor/github.com/containers/image/v5/copy/copy.go:755 +0x3ea
created by github.com/containers/image/v5/copy.(*imageCopier).copyLayers.func2
	vendor/github.com/containers/image/v5/copy/copy.go:766 +0x1b5
```
Even though the error occurs in podman, I opened the issue here because the backtrace suggests that the issue occurs in the `containers/image` code.

The registry is a normal docker registry.

## System Information
```
OS: Debian Buster
Podman Version: Occurs on both version 1.6.2 (installed via ubuntu PPA) and source build of podman (1.6.4-dev)
```

**Comment by mtrmac** [comment]
Thanks for your report.

I can’t immediately see how the code ca can fail this way, and/or how c/image can cause that.

Is this reproducible, and does it always fail in the same place?

What version of Go is used?

**Comment by timonegk** [comment]
The go version is `go1.11.6 linux/amd64`. The push does not always fail, roughly one out of three times, and the failure occurs in different places and for different images (for the same registry, though).

**Comment by mtrmac** [comment]
Could that be https://github.com/golang/go/issues/29517 ? It was fixed on the 1.12 branch, but not in 1.11.

**Comment by timonegk** [comment]
When building go from master and rebuilding podman with the new go version, the problem persists. But since the issue looks very similar to the one you posted, it is probably not related to c/image. I will try to create a minimal example and post it in the golang/go issue tracker.

**Comment by mtrmac** [comment]
The relevant code is https://github.com/containers/image/blob/6bbebfce8b0d40cedb6039e3593c70291a7ae34e/docker/docker_image_dest.go#L160-L169 , ultimately a `h := crypto.SHA256.New()`, repeated `h.Write()`, and `h.Sum(nil)`; one of the very simplest possible uses AFAICS.

**Comment by mtrmac** [comment]
> Could that be [golang/go#29517](https://github.com/golang/go/issues/29517) ?

Oops, it really shouldn’t be that bug, because nothing here uses binary marshaling AFAICS.

**Comment by mtrmac** [comment]
@mpw96
> Is this reproducible, and does it always fail in the same place?

**Comment by timonegk** [comment]
This was somehow related to https://github.com/containers/image/issues/756. When I fixed the Docker Registry nginx config, this issue no longer occurred.

**Comment by mpw96** [comment]
> @mpw96
> 
> > Is this reproducible, and does it always fail in the same place?

@mtrmac thank you for looking into this. Yes, it's **reproducible 100% of the times and always at the same place** if
- the target registry is an Azure ACR and
- I run the skopeo container on a host with 64 processing units (`nproc --all`) and
- No layers of the docker image to upload are already in the ACR: Meaning I must make sure with the Azure Web UI of the ACR to delete the repository. If I just call skopeo again after the failure without deleting the repo on the ACR, the skopeo call succeeds.

Please note:
- It's been working for weeks now on Amazon AWS's ECR (at least 360 successful uploads with no errors) from the big host and from my MacBook
- It works 100% even with Azure ACR of the time when I run the very same skopeo container on my MacBook (`sysctl -n hw.physicalcpu` equals 4)

I've attached all goroutine dumps at the other issue.

T&R
Marc-Philip

**Comment by mpw96** [comment]
> This was somehow related to #756. When I fixed the Docker Registry nginx config, this issue no longer occurred.

@timonegk What exactly did you change in the nginx configuration? Maybe I can just ask Microsoft to do the same?

**Comment by mpw96** [comment]
@timonegk in the trace at containers/skopeo#801 I see `\"Server\":[]string{\"openresty\"}`, so maybe your change in the nginx configuration might actually help here as well, because https://github.com/openresty/openresty is based on nginx.

**Comment by timonegk** [comment]
The settings that I added were
```
client_max_body_size 0;
proxy_max_temp_file_size 0;
chunked_transfer_encoding on;
```

**Comment by juliusl** [comment]
@mpw96 Is it possible to get the output of `lscpu` on both hosts?

**Comment by mpw96** [comment]
I think I have an explanation for containers/skopeo#801:

The registry that I want to copy an image to with skopeo is an **Azure ACR which is geo-replicated**. The "home" replica is westeurope and I have a replica in westus. I am in Germany (obviously westeurope is closest to me).

When I delete the replica in westus, copy from both my Mac and the "big" host work without error. After re-adding the replica in westus, the errors from the "big host" re-occur.  

[This Azure troubleshoot document](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-geo-replication#troubleshoot-push-operations-with-geo-replicated-registries) explains it.

So I figure
- all upload traffic from my laptop goes to the one replica westeurope, but
- as the "big" host is in the cloud, some of its requests go to westeurope, and some to westus.

Regards
MP

**Comment by mtrmac** [comment]
From my point of view, it is fine if the push _fails_, but it should not _crash_.

**Comment by mpw96** [comment]
@mtrmac I extended my testing a bit and call the `skopeo copy` in a loop now. I get one of these three different types of errors now if i have two replicas of the ACR:
```
time='2020-01-22T20:59:38Z' level=fatal msg='Error writing blob: Error uploading layer to https://saphcprod.azurecr.io/v2/com.sap.hana.cloud.cloudinfrastructure/cluster-lifecycle-hooks/blobs/uploads/8273a7b5-797c-478c-b6d8-8da0f6c05c30?_nouploadcache=false&_state=FfezIXqRIj7VGaKPSoFy4X9Y9ss37Bs3db2sdtRHzZd7Ik5hbWUiOiJjb20uc2FwLmhhbmEuY2xvdWQuY2xvdWRpbmZyYXN0cnVjdHVyZS9jbHVzdGVyLWxpZmVjeWNsZS1ob29rcyIsIlVVSUQiOiI4MjczYTdiNS03OTdjLTQ3OGMtYjZkOC04ZGEwZjZjMDVjMzAiLCJPZmZzZXQiOjMzNDksIlN0YXJ0ZWRBdCI6IjIwMjAtMDEtMjJUMjA6NTk6MzJaIn0%3D&digest=sha256%3Ab1ca829135fb96f0bdcfc88aec40f52eae8334d232f3db0992b98886403f6432: blob upload unknown: blob upload unknown to registry'

time='2020-01-22T21:00:12Z' level=fatal msg='Error writing blob: Error determining upload URL: http: no Location header in response'

time='2020-01-22T21:03:09Z' level=fatal msg='Error writing manifest: Error uploading manifest 0.0.1-86.86b711b to saphcprod.azurecr.io/com.sap.hana.cloud.cloudinfrastructure/cluster-lifecycle-hooks: errors:\\nmanifest blob unknown: blob unknown to registry\\nmanifest blob unknown: blob unknown to registry\\nmanifest blob unknown: blob unknown to registry\\nmanifest blob unknown: blob unknown to registry\\nmanifest blob unknown: blob unknown to registry\\n'
```

So the error is one of
- Error uploading layer (crash)
- Error determining upload URL (failure)
- Error writing manifest (failure)

**Comment by mtrmac** [comment]
“blob unknown to registry” would be explained by the Azure document.

I’ve reviewed the SHA256 implementation that is crashing again, and I just can’t see how that code could possibly fail in there.

**Comment by timonegk** [comment]
No location header in response was the same issue I experienced with the misconfigured nginx. Unfortunately, Podman's error messages are not very helpful, Docker instead gave quite useful errors. So maybe pushing with Docker could help finding the other errors too?

**Comment by juliusl** [comment]
@mtrmac, I was thinking shouldn't line 163 return an error if the patch request ultimately fails? 
 https://github.com/containers/image/blob/6bbebfce8b0d40cedb6039e3593c70291a7ae34e/docker/docker_image_dest.go#L163

So that ultimately this function returns before anything is allowed to call panic(). The panic in this case actually has little to do with the actual problem. (Though I don't quite understand the .nx value isn't zeroed right after the padding write.)

**Comment by mpw96** [comment]
Regarding containers/skopeo#801: We seem to have less problems when we upload images if we use `docker push` instead of `skopeo copy` (not possible for our production).

However, I have a question:
Does skopeo resolve the registry name for each layer? Wouldn't it make sense to resolve the name only one time  upfront? I'm asking this because we have a problem with `skopeo copy` when there is more than one possible "target"?

T&R
Marc-Philip

**Comment by mpw96** [comment]
Regarding containers/skopeo#801: I have found a solution along the lines of the [Azure troubleshoot document](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-geo-replication#troubleshoot-push-operations-with-geo-replicated-registries): Before i call `skopeo copy`, I use `dig` to get the ip address of the registry and append a line to `/etc/hosts` of the host that it's running on (which is a docker container itself and is deleted after the call).

I have not had errors since doing it like this.

**Comment by mtrmac** [comment]
A completely unsubstantiated theory, writing it down here just so that it isn’t lost:

We start an upload of the layer (HTTP header+body); for some reason Go moves that to a concurrent goroutine. The server, as soon as it sees the request header, determines that the upload URL is invalid (not synced among all the replicas), and sends an error response, which “terminates” processing the request. At that point, control is returned to the caller and we call `digester.Digest()`  — but the goroutine sending the data has not yet terminated, causing concurrent writes to the `digest.nx` field, which results in a race.

Now
1. Can this happen at all? It used to be possible in the past, per https://github.com/containers/image/blob/d9b1d8e0aa2767ca7abe0d429c4833f96c146b0b/docker/daemon/daemon_dest.go#L104-L109
2. If so, how to prevent that, and ensure the body-sending goroutine terminates?
   (detecting an error response and aborting the upload per https://github.com/containers/image/issues/750#issuecomment-577909751 might _locally_ be good enough — if we leave the body writer running, but we don’t use the digester in the other goroutine. OTOH the rest of the c/image library is not really ready for the stream producing the data to just continue running in the background, I’m worried that just result in even more strange crashes.)
3. At that point, the upload is going to fail, and the code is not quite structured to be able to retry. What to do?

**Comment by nalind** [comment]
Re: 2), if we have an expected stream length (i.e., `inputInfo.Size != -1`), would we be able to wait until `sizeCounter.size` reached that value, give or take a timeout, or return an error, before calling `digester.Digest()`?

**Comment by mtrmac** [comment]
> We start an upload of the layer (HTTP header+body); for some reason Go moves that to a concurrent goroutine. The server, as soon as it sees the request header, determines that the upload URL is invalid (not synced among all the replicas), and sends an error response, which “terminates” processing the request. At that point, control is returned to the caller and we call `digester.Digest()` — but the goroutine sending the data has not yet terminated, causing concurrent writes to the `digest.nx` field, which results in a race.

Confirmed this can happen:

<details>
<summary>Test+output</summary>

```go
func failingHandler(w http.ResponseWriter, _ *http.Request) {
	http.Error(w, "Error", http.StatusInternalServerError)
}

type largeReader struct {
	remaining int64
}

func (r *largeReader) Read(p []byte) (int, error) {
	logrus.Infof("Read %v", len(p))
	if r.remaining == 0 {
		return 0, io.EOF
	}
	n := len(p)
	if int64(n) > r.remaining {
		n = int(r.remaining)
	}
	for i := 0; i < n; i++ {
		p[i] = 0x01
	}
	r.remaining -= int64(n)
	return n, nil
}

func TestRequestCancellation(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(failingHandler))
	defer func() {
		logrus.Info("Closing…")
		server.Close()
		logrus.Info("Closed")
	}()

	client := http.Client{}

	totalSize := int64(1000000000)
	body := &largeReader{remaining: totalSize}
	logrus.Info("NewRequest:")
	req, err := http.NewRequest(http.MethodPatch, server.URL, body)
	require.NoError(t, err)
	req.ContentLength = totalSize
	logrus.Info("Do…")
	res, err := client.Do(req)
	logrus.Info("…Do")
	require.NoError(t, err)
	defer res.Body.Close()
	logrus.Infof("Status %v", res.StatusCode)
}
```

```console
 % go test -v -run Cancellation  ./docker
=== RUN   TestRequestCancellation
time="2020-04-03T21:29:00+02:00" level=info msg="NewRequest:"
time="2020-04-03T21:29:00+02:00" level=info msg="Do…"
time="2020-04-03T21:29:00+02:00" level=info msg="Read 32768"
time="2020-04-03T21:29:00+02:00" level=info msg="Read 32768"
time="2020-04-03T21:29:00+02:00" level=info msg="Read 32768"
time="2020-04-03T21:29:00+02:00" level=info msg="Read 32768"
time="2020-04-03T21:29:00+02:00" level=info msg="Read 32768"
time="2020-04-03T21:29:00+02:00" level=info msg="…Do"
time="2020-04-03T21:29:00+02:00" level=info msg="Status 500"
time="2020-04-03T21:29:00+02:00" level=info msg="Closing…"
time="2020-04-03T21:29:00+02:00" level=info msg="Read 32768"
time="2020-04-03T21:29:01+02:00" level=info msg=Closed
--- PASS: TestRequestCancellation (0.50s)
PASS
ok  	github.com/containers/image/v5/docker	0.643s
```
</details>

**Comment by mtrmac** [comment]
FWIW in one case the problem replicated registries turned out to be a missing shared `secret` value, which must be the same across all replicas (see https://github.com/docker/distribution/blob/master/docs/configuration.md#http ).

Still, of course, c/image should report the error back correctly instead of crashing.

**Comment by mtrmac** [comment]
<details>
<summary>For the record, a way to trigger the panic (but invalid use of the net/http server API, so not suitable for tests)</summary>

```go
package docker

import (
	"context"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/containers/image/v5/pkg/blobinfocache/memory"
	"github.com/containers/image/v5/types"
	"github.com/sirupsen/logrus"

	// "github.com/sirupsen/logrus"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// largeJunkRearder provides a long stream of data to test the handling of aborted uploads.
type largeJunkReader struct {
	remaining int64
}

func (r *largeJunkReader) Close() error {
	return nil
}

func (r *largeJunkReader) Read(p []byte) (int, error) {
	if r.remaining == 0 {
		return 0, io.EOF
	}
	n := len(p)
	if int64(n) > r.remaining {
		n = int(r.remaining)
	}
	// Try hard to misalign the output to trigger inconsistency in the sha256 code on race
	if n >= 2 && n%2 == 0 {
		n--
	}
	for i := 0; i < n; i++ {
		p[i] = 0x01
	}
	r.remaining -= int64(n)
	return n, nil
}

func TestDockerImageDestinationPutBlob(t *testing.T) {
	const repoName = "ns/repo"

	var serverURL string
	fakeRegistry := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		const uploadLocation = "/upload/location/aa55"
		switch {
		case req.URL.Path == "/v2/" && req.Method == http.MethodGet:
			w.WriteHeader(http.StatusOK)
		case req.URL.Path == "/v2/"+repoName+"/blobs/uploads/" && req.Method == http.MethodPost:
			w.Header().Set("Location", serverURL+uploadLocation)
			w.WriteHeader(http.StatusAccepted)
		case req.URL.Path == uploadLocation && req.Method == http.MethodPatch:
			http.Error(w, `{"errors":[{"code": "BLOB_UPLOAD_UNKNOWN"}]}`, http.StatusNotFound)
			// This is INVALID
			go func() {
				_, _ = io.Copy(ioutil.Discard, req.Body)
			}()
		// 	if _, err := io.Copy(ioutil.Discard, req.Body); err != nil {
		// 		http.Error(w, fmt.Sprintf("Error reading content: %v", err), http.StatusInternalServerError)
		// 		return
		// 	}
		// 	w.Header().Set("Location", serverURL+uploadLocation)
		// 	w.WriteHeader(http.StatusAccepted)
		// case req.URL.Path == uploadLocation && req.Method == http.MethodPut:
		// 	w.WriteHeader(http.StatusCreated)
		default:
			assert.Fail(t, "Unhandled server stub", "method+URL %v %q", req.Method, req.URL.String())
			http.Error(w, fmt.Sprintf("Unhandled method+URL %v %q", req.Method, req.URL.String()), http.StatusInternalServerError)
		}
	}))
	defer fakeRegistry.Close()
	serverURL = fakeRegistry.URL

	ref, err := ParseReference("//" + fakeRegistry.Listener.Addr().String() + "/" + repoName)
	require.NoError(t, err)
	dest, err := ref.NewImageDestination(context.Background(),
		&types.SystemContext{DockerInsecureSkipTLSVerify: types.OptionalBoolTrue})
	require.NoError(t, err)

	input := &largeJunkReader{remaining: 1000000}
	_, err = dest.PutBlob(context.Background(), input, types.BlobInfo{Size: -1}, memory.New(), false)
	// This should fail, but not crash
	assert.Error(t, err)
}
```
</details>

**Comment by mtrmac** [comment]
Anyone who can reproduce this, please test https://github.com/containers/image/pull/907 .
